### PR TITLE
Code standard

### PR DESCRIPTION
**Pull request by jpatton-USGS**
**What kind of changes does this PR introduce?** 
This PR implements the following from the roadmap for operationalizing the locator: loading from a specified input file, implementing the LocService interface, integrating with [earthquake-processing-formats](https://github.com/usgs/earthquake-processing-formats) for json input/output, applying the NEIC coding standards, and formatting the code according to the google code style.

Iterative tests were made prior to each commit to confirm that the algorithm's output matched the output provided by the original author.

The `checkstyle-8.18-all.jar` and `google-java-format-1.7-all-deps.jar` tools were used to assist with applying the google style.

Pretty much every line of code has been changed in some way, so the more eyes the better, both from a code standard perspective and best java practices.

@mguy-usgs @buland-usgs @jmfee-usgs

### CODE REVIEW

**Comment by jpatton-USGS** [comment]
I added the logging changes to this PR.

**Comment by jpatton-USGS** [comment]
Additionally, when it comes time, I recommend that we Squash and Merge this PR.

**Comment by bemielke** [comment]
I didn't see any major issues when reviewing the code.  I would review the Codacy review as there are a few things in there that may be worth looking at, one of the ones being to make sure and use .equals() when comparing strings and when comparing to a literal do it in the form of "literal".equals(variable) to avoid null pointer exceptions.  

Additionally some of the loops could be replaced with more recent looping methods like the new for each formats.   I wouldn't bother with this though unless some other changes were needed.

I was going to suggest perhaps implementing logging instead of system.out, but I see that code was just added so I will take a look at it.

I did see an occassion try catch RuntimeException which might be a little broad in some cases, and when done it would probably be best to log the actual exception in case it isn't the case that you are attempting to ignore.

**Comment by jpatton-USGS** [comment]
I will work on the codacy issues

**Comment by jpatton-USGS** [comment]
I have addressed all the codacy issues I think I can without drastically refactoring Ray's algorithm to shorten / simplify the flagged methods.

**Comment by jmfee-usgs** [comment]
Build currently fails.  Also, please update travis config to run gradle build

```
$ gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileJava FAILED
neic-locator/src/main/java/gov/usgs/locator/Decorrelator.java:400: error: ';' expected
          return Math.abs(weightedResiduals.getSpatialDerivatives()[2]) > 1e-4d);
                                                                               ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Pull request merged**
